HammerDB Db2tcl
memmertoIBM/db2tcl pull request #5
Opened 2021-01-14 15:09 UTC by sm-shaw

Changes made to the original db2tcl source that is used in HammerDB and is named as Db2tcl 2.0.0 when the package is loaded. Changes included adding commands and also adding support to build a DLL to support Db2 on windows.

2021-03-02 22:01 UTC, memmertoIBM requested changes

2021-03-02 22:01 UTC, memmertoIBM commented on src/db2tclcmds.c
> +    Tcl_EventuallyFree ((ClientData) conn->rc, TCL_DYNAMIC);
conn->rc is NOT an object.  The old code looks more correct, given the purpose of Tcl_EventuallyFree().

2021-03-04 13:56 UTC, sm-shaw commented on src/db2tclcmds.c
> +    Tcl_EventuallyFree ((ClientData) conn->rc, TCL_DYNAMIC);
This looks like a great example of why you should comment source code changes!  Not entirely sure why this change was made. I do recall something to do with EventuallyFree when running it but cannot be certain so will change the PR.

2021-03-04 14:03 UTC, sm-shaw commented on src/db2tclcmds.c
> +    Tcl_EventuallyFree ((ClientData) conn->rc, TCL_DYNAMIC);
Requested change has been made.

2021-03-09 21:18 UTC, memmertoIBM approved these changes

2021-03-09 21:18 UTC, merged

2021-03-09 21:19 UTC, memmertoIBM commented
Resolves #2.